// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/dairyo/compiledrepo (interfaces: Opener)
//
// Generated by this command:
//
//	mockgen -destination=mock_opener_test.go -package=compiledrepo . Opener
//

// Package compiledrepo is a generated GoMock package.
package compiledrepo

import (
	context "context"
	io "io"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockOpener is a mock of Opener interface.
type MockOpener[K comparable, R io.ReadCloser] struct {
	ctrl     *gomock.Controller
	recorder *MockOpenerMockRecorder[K, R]
	isgomock struct{}
}

// MockOpenerMockRecorder is the mock recorder for MockOpener.
type MockOpenerMockRecorder[K comparable, R io.ReadCloser] struct {
	mock *MockOpener[K, R]
}

// NewMockOpener creates a new mock instance.
func NewMockOpener[K comparable, R io.ReadCloser](ctrl *gomock.Controller) *MockOpener[K, R] {
	mock := &MockOpener[K, R]{ctrl: ctrl}
	mock.recorder = &MockOpenerMockRecorder[K, R]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOpener[K, R]) EXPECT() *MockOpenerMockRecorder[K, R] {
	return m.recorder
}

// Open mocks base method.
func (m *MockOpener[K, R]) Open(ctx context.Context, key K) (R, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Open", ctx, key)
	ret0, _ := ret[0].(R)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Open indicates an expected call of Open.
func (mr *MockOpenerMockRecorder[K, R]) Open(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Open", reflect.TypeOf((*MockOpener[K, R])(nil).Open), ctx, key)
}
