// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/dairyo/compiledrepo (interfaces: KeyIterator)
//
// Generated by this command:
//
//	mockgen -destination=mock_keyiterator_test.go -package=compiledrepo . KeyIterator
//

// Package compiledrepo is a generated GoMock package.
package compiledrepo

import (
	context "context"
	iter "iter"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockKeyIterator is a mock of KeyIterator interface.
type MockKeyIterator[K comparable] struct {
	ctrl     *gomock.Controller
	recorder *MockKeyIteratorMockRecorder[K]
	isgomock struct{}
}

// MockKeyIteratorMockRecorder is the mock recorder for MockKeyIterator.
type MockKeyIteratorMockRecorder[K comparable] struct {
	mock *MockKeyIterator[K]
}

// NewMockKeyIterator creates a new mock instance.
func NewMockKeyIterator[K comparable](ctrl *gomock.Controller) *MockKeyIterator[K] {
	mock := &MockKeyIterator[K]{ctrl: ctrl}
	mock.recorder = &MockKeyIteratorMockRecorder[K]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockKeyIterator[K]) EXPECT() *MockKeyIteratorMockRecorder[K] {
	return m.recorder
}

// All mocks base method.
func (m *MockKeyIterator[K]) All(ctx context.Context) iter.Seq2[K, error] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "All", ctx)
	ret0, _ := ret[0].(iter.Seq2[K, error])
	return ret0
}

// All indicates an expected call of All.
func (mr *MockKeyIteratorMockRecorder[K]) All(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "All", reflect.TypeOf((*MockKeyIterator[K])(nil).All), ctx)
}
