// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/dairyo/compiledrepo (interfaces: Opener,Compiler)
//
// Generated by this command:
//
//	mockgen -destination=mocks_test.go -package=compiledrepo . Opener,Compiler
//

// Package compiledrepo is a generated GoMock package.
package compiledrepo

import (
	context "context"
	io "io"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockOpener is a mock of Opener interface.
type MockOpener[K comparable, R io.ReadCloser] struct {
	ctrl     *gomock.Controller
	recorder *MockOpenerMockRecorder[K, R]
	isgomock struct{}
}

// MockOpenerMockRecorder is the mock recorder for MockOpener.
type MockOpenerMockRecorder[K comparable, R io.ReadCloser] struct {
	mock *MockOpener[K, R]
}

// NewMockOpener creates a new mock instance.
func NewMockOpener[K comparable, R io.ReadCloser](ctrl *gomock.Controller) *MockOpener[K, R] {
	mock := &MockOpener[K, R]{ctrl: ctrl}
	mock.recorder = &MockOpenerMockRecorder[K, R]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOpener[K, R]) EXPECT() *MockOpenerMockRecorder[K, R] {
	return m.recorder
}

// Open mocks base method.
func (m *MockOpener[K, R]) Open(ctx context.Context, key K) (R, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Open", ctx, key)
	ret0, _ := ret[0].(R)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Open indicates an expected call of Open.
func (mr *MockOpenerMockRecorder[K, R]) Open(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Open", reflect.TypeOf((*MockOpener[K, R])(nil).Open), ctx, key)
}

// MockCompiler is a mock of Compiler interface.
type MockCompiler[R io.ReadCloser, V any] struct {
	ctrl     *gomock.Controller
	recorder *MockCompilerMockRecorder[R, V]
	isgomock struct{}
}

// MockCompilerMockRecorder is the mock recorder for MockCompiler.
type MockCompilerMockRecorder[R io.ReadCloser, V any] struct {
	mock *MockCompiler[R, V]
}

// NewMockCompiler creates a new mock instance.
func NewMockCompiler[R io.ReadCloser, V any](ctrl *gomock.Controller) *MockCompiler[R, V] {
	mock := &MockCompiler[R, V]{ctrl: ctrl}
	mock.recorder = &MockCompilerMockRecorder[R, V]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCompiler[R, V]) EXPECT() *MockCompilerMockRecorder[R, V] {
	return m.recorder
}

// Compile mocks base method.
func (m *MockCompiler[R, V]) Compile(ctx context.Context, r R) (V, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Compile", ctx, r)
	ret0, _ := ret[0].(V)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Compile indicates an expected call of Compile.
func (mr *MockCompilerMockRecorder[R, V]) Compile(ctx, r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Compile", reflect.TypeOf((*MockCompiler[R, V])(nil).Compile), ctx, r)
}
