// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/dairyo/compiledrepo (interfaces: Compiler)
//
// Generated by this command:
//
//	mockgen -destination=mock_compiler_test.go -package=compiledrepo . Compiler
//

// Package compiledrepo is a generated GoMock package.
package compiledrepo

import (
	context "context"
	io "io"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockCompiler is a mock of Compiler interface.
type MockCompiler[R io.Reader, V any] struct {
	ctrl     *gomock.Controller
	recorder *MockCompilerMockRecorder[R, V]
	isgomock struct{}
}

// MockCompilerMockRecorder is the mock recorder for MockCompiler.
type MockCompilerMockRecorder[R io.Reader, V any] struct {
	mock *MockCompiler[R, V]
}

// NewMockCompiler creates a new mock instance.
func NewMockCompiler[R io.Reader, V any](ctrl *gomock.Controller) *MockCompiler[R, V] {
	mock := &MockCompiler[R, V]{ctrl: ctrl}
	mock.recorder = &MockCompilerMockRecorder[R, V]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCompiler[R, V]) EXPECT() *MockCompilerMockRecorder[R, V] {
	return m.recorder
}

// Compile mocks base method.
func (m *MockCompiler[R, V]) Compile(ctx context.Context, r R) (V, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Compile", ctx, r)
	ret0, _ := ret[0].(V)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Compile indicates an expected call of Compile.
func (mr *MockCompilerMockRecorder[R, V]) Compile(ctx, r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Compile", reflect.TypeOf((*MockCompiler[R, V])(nil).Compile), ctx, r)
}
